version: "3.8"
services:
  backend:
    image: "korayguney/bilgeadam-fullstack:31.5.2021.12.45.23"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: prod