version: "3.8"
services:
  backend:
    image: "korayguney/bilgeadam-fullstack:30.5.2021.9.27.58"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: prod